version: "3"
services:
  server:
    image: yandex/clickhouse-server
    ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
    environment:                                # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:                                    # 数据卷挂载路径设置,将本机目录映射到容器目录 (下面映射可在容器中执行宿主机docker命令)
      - "./data:/var/lib/clickhouse"
      - "./config.xml:/etc/clickhouse-server/config.xml"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']