version: "3.3"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

