version: '3'
services:
  redis:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: aisino
      RABBITMQ_DEFAULT_PASS: aisino@123
    volumes:
      - "./data:/var/lib/rabbitmq"
    ports:                              # 映射端口
      - "5672:5672"
      - "15672:15672"
