apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

#plugin_attr:
#  prometheus:
#    export_addr:
#      ip: "0.0.0.0"
#      port: 9091

discovery:
  nacos:
    host:
      - "http://192.168.8.212:8848"
    prefix: "/nacos/v1/"
    fetch_interval: 30    # default 30 sec
    weight: 100           # default 100
    timeout:
      connect: 2000       # default 2000 ms
      send: 2000          # default 2000 ms
      read: 5000          # default 5000 ms

nginx_config:
  http_configuration_snippet: |
   server
        {
            listen 80;
            server_name _;
            access_log off;
            location / {
               root /usr/share/nginx/html;
               try_files $uri $uri/ =404;
               index  index.html index.htm;
            }

            location /ysec_status {
                allow 127.0.0.1;
                deny all;
            }
        }
