version: '3'
services:
  mysql:
    image: mysql:5.7.31
    container_name: mysql                                        # 容器名为'mysql'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/etc/localtime:/etc/localtime:ro"
      - "./my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
      - "./conf.d:/etc/mysql/conf.d"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: test              # 初始化的数据库名称
    ports:                              # 映射端口
      - "3306:3306"
