version: '3.1'
services:
  gogs:
    container_name: gogs
    image: docker.io/gogs/gogs:latest
    hostname: gogs
    restart: always
    ports:
      - "1022:22"
      - "3000:3000"
    links:
      - mysql-gogs:mysql
    volumes:
      - ./opt/docker/gogs/:/data/docker/gogs
    networks:
      gogs:
        ipv4_address: 172.18.0.40

    mysql-gogs:
      container_name: mysql-gogs
      image: docker.io/mysql:5.7.25
      hostname: mysql-gogs
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - ./mysql-gogs/mysql:/var/lib/mysql
        - ./mysql-gogs/conf.d:/etc/mysql/conf.d:rw
      environment:
        - MYSQL_DATABASE=gogs
        - MYSQL_USER=gogs
        - MYSQL_PASSWORD=gogs
        - MYSQL_ROOT_PASSWORD=Report@123
      command:
        --lower_case_table_names=1
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --sql-mode=STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      networks:
        gogs:
          ipv4_address: 172.18.0.41
networks:
  gogs:
    external: true