version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
#    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly yes
    command: redis-server --requirepass 123456 --appendonly yes
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./data:/data"
      - "./redis.conf:/etc/redis/redis.conf"  # `redis.conf`文件内容`http://download.redis.io/redis-stable/redis.conf`
    ports: 
      - "6379:6379"
