version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:2.6.3
    container_name: pulsar
    restart: always
    volumes:
      - "$PWD/data:/pulsar/data"
    #  - "$PWD/conf:/pulsar/conf"
    environment:
    #  - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      - TZ="Asia/Shanghai"
      - LANGZ="en_US.UTF-8"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    ports:                              # 映射端口
      - "6650:6650"
      - "6680:8080"
  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar
    ports:
      - "6780:80"
    environment:
      - SERVICE_URL=http://pulsar:8080
